package app;

import java.io.ByteArrayOutputStream;
import java.io.ObjectOutputStream;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import javax.swing.JOptionPane;

public class Cliente extends javax.swing.JFrame {
    
    String ipt;

    public Cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        wordBox = new javax.swing.JTextField();
        eai = new javax.swing.JRadioButton();
        iae = new javax.swing.JRadioButton();
        rspBox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TRADUCTOR");

        wordBox.setText("palabra");
        wordBox.setToolTipText("");
        wordBox.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        wordBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                wordBoxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                wordBoxKeyTyped(evt);
            }
        });

        buttonGroup1.add(eai);
        eai.setSelected(true);
        eai.setText("Español a Ingles");

        buttonGroup1.add(iae);
        iae.setText("Ingles a Español");

        rspBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rspBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("Bienvenido a Traductor UDP");

        jMenu1.setText("Configuracion");

        jMenuItem1.setText("Ip Servidor");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(eai))
                    .addComponent(wordBox, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iae)
                    .addComponent(rspBox, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iae)
                    .addComponent(eai))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rspBox, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(wordBox))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        ipt = JOptionPane.showInputDialog("Ip del servidor");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void wordBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wordBoxKeyTyped
        // TODO add your handling code here:
        //aqui va el codigo
        //if(wordBox.getText().length() == 0) {
          //  rspBox.setText("");
        //}
        
        //ENVIAR LA PALABRA A TRADUCIR
        try {
            InetAddress ip = InetAddress.getByName(ipt);

            DatagramSocket udp = new DatagramSocket();

            dataTR d = new dataTR();
            d.palabra = wordBox.getText();

            if (eai.isSelected()) {
                d.tipo = 1;
            } else {
                d.tipo = 0;
            }

            byte[] mensaje = Transfer.bytes(d);

            //Creacion de datagrama
            DatagramPacket data = new DatagramPacket(mensaje, mensaje.length, ip, 5001);

            //Enviamos
            udp.send(data);

            //Recibimos la traduccion
            byte[] bff = new byte[256];
            DatagramPacket rsp = new DatagramPacket(bff, bff.length);

            //Recibo la respuesta
            udp.receive(rsp);

            //CONVERTIR DE BYTES A OBJETO dataTR
            dataTR r = Transfer.objeto(rsp.getData());
            
            //MOSTRAR PALABRA TRADUCIDA
            rspBox.setText(r.palabra);

            udp.close();

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }

    }//GEN-LAST:event_wordBoxKeyTyped

    private void rspBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rspBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rspBoxActionPerformed

    private void wordBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wordBoxKeyReleased
        // TODO add your handling code here:
        if(wordBox.getText().length() == 0) {
           rspBox.setText("");
        }
    }//GEN-LAST:event_wordBoxKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton eai;
    private javax.swing.JRadioButton iae;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTextField rspBox;
    private javax.swing.JTextField wordBox;
    // End of variables declaration//GEN-END:variables
}
